categories:
  - id: engine
    name: Engine
    paths:
      - bodyprog
  - id: sdk
    name: Psy-Q SDK
    paths:
      - bodyprog/psyq
      - main/psyq
      - screens/stream/psyq
  - id: map
    name: Map Overlays
    paths:
      - maps
  - id: main
    name: Main Executable
    paths:
      - main
  - id: screens
    name: Konami Boot Screen
    paths:
      - screens/b_konami
    name: Credits Screen
    paths:
      - screens/credits
    name: Options Screen
    paths:
      - screens/options
    name: Save and Load Screen
    paths:
      - screens/saveload
    name: FMVs Logic
    paths:
      - screens/stream

expected_paths:
  asm: expected/asm
  src: expected/src

ignored_files:
  - main/header

output: ./objdiff.json
