categories:
  - id: engine
    name: Engine
    paths:
      - bodyprog
  - id: sdk
    name: Psy-Q SDK
    paths:
      - bodyprog/psyq
      - main/psyq
      - screens/stream/psyq
  - id: main
    name: Main Executable
    paths:
      - main
  - id: screen
    name: Game Screens
    paths:
      - screens
  - id: map
    name: Map Overlays
    paths:
      - maps

expected_paths:
  asm: expected/asm
  src: expected/src

ignored_files:
  - main/header

output: ./objdiff.json
