name: Main Executable (SLUS_007.07)
sha1: f38344565fb731befc52fd968eb5a667be37acf3
options:
  basename: SLUS_007.07
  target_path: rom/SLUS_007.07
  base_path: ..
  platform: psx
  compiler: GCC

  asm_path: asm/main
  src_path: src/
  build_path: build/
  # create_asm_dependencies: True

  ld_script_path: linkers/SLUS_007.07.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  symbol_addrs_path:
    - meta/SLUS_007.07.symbol_addrs.txt
  reloc_addrs_path:
    - meta/SLUS_007.07.reloc_addrs.txt

  undefined_funcs_auto_path: meta/SLUS_007.07.undefined_funcs_auto.txt
  undefined_syms_auto_path: meta/SLUS_007.07.undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subalign: 4
    # bss_size: 0x1EC8
    subsegments:
      - [0x800, .rodata, main]
      - [0x830, rodata, psyq]
      - [0xF70, c, main]
      - [0x29BC, asm, psyq]
      - [0xB91C, data, main]
      - [0x11B4C, data, psyq]
      - [0x133B0, sdata, main]
      - [0x13494, sbss, psyq]
      - [0x13498, bss]
      # produces errors during build
      # - { start: 0x13498, type: bss, vram: 0x80022c98, name: main }
      # - { start: 0x139B8, type: bss, vram: 0x800231a0, name: psyq }
  - [0x14000]
