name: Determine and Push Progress

on:
  push:

jobs:
  build:
    container: ghcr.io/vatuu/decomp-images-silent-hill:master

    strategy:
      fail-fast: true
      matrix:
        game_id: [ SLUS-00707 ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Setup Python"
        run: pip3 install -r requirements.txt --break-system-packages

      - name: "Copy ROM"
        run: cp -p /rom ./image/rom

      - run: ls
      - run: ls /rom
      - run: ls ./rom/image

      - name: Setup Environment
        run: make setup

      - name: Generate Progress
        run: make progress

      - name: Upload Progress Report
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.game_id }}_report
            path: ./build/progress.json
      

